### ISSUE TITLE
Mozilla's RegretsReporter dataset?

### ISSUE THREAD

**Issue by mehanix** [Algorithmic-Alignment-Lab/Regrets#1]
Hi, I saw your lightning talk at 38c3 but couldn't note your contact details in time.

I was just wondering if you know about the RegretsReporter extension by Mozilla and the dataset they have and if you've tried using it?

https://foundation.mozilla.org/en/youtube/regretsreporter-dataset/

Also, if you see this in time, would be curious to chat more about this at the congress.

Good luck!

**Comment by Indraos** [comment]
Hi @mehanix!
yes, we did talk with them a while back! The differences to Mozilla's Youtube Regrets (YR) extension are:
 - The data collection: YR allows users to click "don't recommend" on a result page, so before being able to 'regret' it. The data collection tool here is retrospective about what people watched. In doing so, for a user it allows for reflection, for an algorithm it allows to get additional context (the user regrets) to a consumption of a video.
 - The intended use: The tool not merely signals regretted content to Youtube, but intends to filter content that might be regretted for users.
